// app/layout.js
import './globals.css';
import { Creepster } from 'next/font/google';

const creepster = Creepster({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-creepster',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={creepster.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
