// app/layout.js
import "./globals.css";
import { Creepster } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartProvider } from "@/contexts/CartContext";
import { SearchProvider } from "@/contexts/SearchContext";
import SearchModal from "@/components/SearchModal";

const creepster = Creepster({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-creepster",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${creepster.variable}
    `}
    >
      <body className="min-h-screen flex flex-col">
        <CartProvider>
          <SearchProvider>
            <Header />
            <main className="flex-1 pt-[60px]">
              {children}
            </main>
            <Footer />
            <SearchModal />
          </SearchProvider>
        </CartProvider>
      </body>
    </html>
  );
}
